(defun exc3 (a b c)
  (if (> a b)
      (if (> b c)
          (+ (* a a) (* b b))
          (+ (* a a) (* c c)))
      (if (> b c)
          (if (> a c)
              (+ (* a a) (* b b))
              (+ (* b b) (* c c)))
          (if (> a c)
              (+ (* a a) (* b b))
              (+ (* b b) (* c c))))))
